apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: vimkbbr9l-nodejs-gitops
  description: This is GitOps manifest for vimkbbr9l-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: vimkbbr9l-nodejs
    backstage.io/kubernetes-id: vimkbbr9l-nodejs 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: vimkbbr9l-nodejs-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:vimkbbr9l-nodejs
